### ISSUE TITLE
Add population as denominator in Cases/Deaths in Selected Counties

### ISSUE THREAD

**Issue by toychchen** [owenchu/corona-cases#13]
We can keep total cases and add percentage, like 122,168/39,510,000 (0.309%)

However, I am not sure which way is better for death.
Deaths/Populations or Deaths/Cases?

**Comment by owenchu** [comment]
https://www.census.gov/data/datasets/time-series/demo/popest/2010s-counties-total.html

**Comment by owenchu** [comment]
34f386b3dd114d477a909cf46b8022450e68effa added population data.
