### ISSUE TITLE
There is an unknown county covering FL map

### ISSUE THREAD

**Issue by toychchen** [owenchu/corona-cases#4]
Between Glades and Palm Beach, there is a strange blue county covering other FL's counties.

**Comment by owenchu** [comment]
That's Lake Okeechobee: https://goo.gl/maps/h9hEmAdfaMQLUywr8.

**Comment by toychchen** [comment]
then, maybe white would be less confuse.

**Comment by toychchen** [comment]
hmm... just let it be if the .svg colored it as blue.
